apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: cangeles
  labels:
    app: app
spec:
  replicas: 1
  strategy:
    type: Recreate
  minReadySeconds: 20
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: db-secret
        name: app-deployment
        image: harbor.dev.afsmtddso.com/cangeles-harbor-project/app@sha256:d3a965f4efa3e54d71c7049ea4a9aede9b81e7593ef7d91fa365c878010e7711
        ports:
        - containerPort: 5000
